#!/usr/bin/env bash

# Terminate script on error
set -e

# Get the source directory
# (This may not be portable.)
src_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "=== Newsboat ==="

echo "Exporting Newsboat RSS subscriptions to OPML..."
newsboat -e > "$src_dir/autogenerated/exported-subscriptions.xml"

echo "DONE!"
printf "\n"
